# Generated by Django 2.0.4 on 2018-04-14 02:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ants', '0004_auto_20180404_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotting_type', models.CharField(choices=[('F', 'Nuptial Flight'), ('Q', 'Queen')], max_length=1)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('humidity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('ant_regions', models.ManyToManyField(related_name='flights', to='ants.AntRegion')),
                ('ant_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='ants.AntSpecies')),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('unit', models.CharField(choices=[('C', '°C'), ('F', '°F')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Velocity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('KMH', 'km/h'), ('MPH', 'mph')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='temperature',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='flights.Temperature'),
        ),
        migrations.AddField(
            model_name='flight',
            name='wind_speed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='flights.Velocity'),
        ),
    ]
