# Generated by Django 2.0.4 on 2018-04-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
