# Generated by Django 2.0.5 on 2018-05-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0002_flight_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="reviewed",
            field=models.BooleanField(default=False),
        ),
    ]
