# Generated by Django 2.0.5 on 2018-05-21 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0005_auto_20180521_2146"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flight",
            old_name="county_long",
            new_name="county",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="county_short",
        ),
    ]
