# Generated by Django 2.0.5 on 2018-05-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_flight_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='state_long',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='state_short',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
