# Generated by Django 2.0.5 on 2018-05-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0009_auto_20180527_0036"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="address",
            field=models.CharField(max_length=200),
        ),
    ]
