# Generated by Django 2.0.5 on 2018-05-30 04:17

import datetime

import django.core.validators
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0012_auto_20180529_0754"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="rain",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NO", "No rain"),
                    ("DURING", "Rain during spotting"),
                    ("BEFORE", "Rain before spotting"),
                    ("AFTER", "Rain after spotting"),
                ],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="date",
            field=models.DateField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        datetime.date(2018, 5, 30),
                        "Date has to be today or lie in the past.",
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="habitat",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
