# Generated by Django 2.0.5 on 2018-05-30 08:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0013_auto_20180530_0617"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flight",
            old_name="habitat",
            new_name="habitats",
        ),
    ]
