# Generated by Django 2.0.5 on 2018-05-30 08:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0014_auto_20180530_1002"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flight",
            old_name="habitats",
            new_name="habitat",
        ),
    ]
