# Generated by Django 2.0.5 on 2018-06-01 05:59

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0021_flight_species_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="date",
            field=models.DateField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        datetime.date(2018, 6, 1),
                        "Date has to be today or lie in the past.",
                    )
                ]
            ),
        ),
    ]
