# Generated by Django 2.0.5 on 2018-06-01 06:06

from django.db import migrations, models
import flights.models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0022_auto_20180601_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateField(validators=[flights.models.validate_date_today_or_earlier]),
        ),
    ]
