# Generated by Django 2.0.6 on 2018-06-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0023_auto_20180601_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='external_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='project',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
