# Generated by Django 2.0.7 on 2018-07-11 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0027_flight_location_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flight",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="flight",
            name="location_type",
            field=models.CharField(
                choices=[("ADDR", "Address"), ("LATLNG", "Latitude/Longitude")],
                default="ADDR",
                max_length=6,
            ),
        ),
    ]
