# Generated by Django 2.0.7 on 2018-07-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0028_auto_20180711_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
