# Generated by Django 2.0.2 on 2018-03-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='ant_list_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='region',
            name='ant_list_complete',
            field=models.BooleanField(default=False),
        ),
    ]
