# Generated by Django 2.0.6 on 2018-06-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_region_official_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(default='blub', editable=False),
            preserve_default=False,
        ),
    ]
