# Generated by Django 2.0.2 on 2018-03-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_auto_20180304_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(db_index=True, max_length=3, verbose_name='Country code'),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
