# Generated by Django 2.0.2 on 2018-03-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_auto_20180308_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(db_index=True, max_length=8, verbose_name='ISO Code'),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(db_index=True, max_length=8, verbose_name='ISO Code'),
        ),
    ]
