# Generated by Django 3.2.2 on 2021-05-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0004_auto_20180912_2138"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=8,
                null=True,
                verbose_name="ISO Code",
            ),
        ),
    ]
