# Generated by Django 2.0.3 on 2018-03-24 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0006_auto_20180324_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
