# Generated by Django 2.0.3 on 2018-03-28 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0007_auto_20180324_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['type', 'name'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterField(
            model_name='region',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='regions.Region'),
        ),
    ]
