# Generated by Django 2.0.3 on 2018-03-29 10:55

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AntRegion",
            fields=[
                (
                    "region_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regions.Region",
                    ),
                ),
                ("ant_list_complete", models.BooleanField(default=False)),
            ],
            bases=("regions.region",),
        ),
        migrations.CreateModel(
            name="AntSize",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("WORKER", "Worker"),
                            ("QUEEN", "Queen"),
                            ("MALE", "Male"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Minimum (mm)",
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Maximum (mm)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommonName",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("af", "Afrikaans"),
                            ("sq", "Albanian"),
                            ("ar", "Arabic"),
                            ("es-ar", "Argentinian Spanish"),
                            ("ast", "Asturian"),
                            ("en-au", "Australian English"),
                            ("az", "Azerbaijani"),
                            ("eu", "Basque"),
                            ("be", "Belarusian"),
                            ("bn", "Bengali"),
                            ("bs", "Bosnian"),
                            ("pt-br", "Brazilian Portuguese"),
                            ("br", "Breton"),
                            ("en-gb", "British English"),
                            ("bg", "Bulgarian"),
                            ("my", "Burmese"),
                            ("ca", "Catalan"),
                            ("es-co", "Colombian Spanish"),
                            ("hr", "Croatian"),
                            ("cs", "Czech"),
                            ("da", "Danish"),
                            ("nl", "Dutch"),
                            ("en", "English"),
                            ("eo", "Esperanto"),
                            ("et", "Estonian"),
                            ("fi", "Finnish"),
                            ("fr", "French"),
                            ("fy", "Frisian"),
                            ("gl", "Galician"),
                            ("ka", "Georgian"),
                            ("de", "German"),
                            ("el", "Greek"),
                            ("he", "Hebrew"),
                            ("hi", "Hindi"),
                            ("hu", "Hungarian"),
                            ("is", "Icelandic"),
                            ("io", "Ido"),
                            ("id", "Indonesian"),
                            ("ia", "Interlingua"),
                            ("ga", "Irish"),
                            ("it", "Italian"),
                            ("ja", "Japanese"),
                            ("kab", "Kabyle"),
                            ("kn", "Kannada"),
                            ("kk", "Kazakh"),
                            ("km", "Khmer"),
                            ("ko", "Korean"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("dsb", "Lower Sorbian"),
                            ("lb", "Luxembourgish"),
                            ("mk", "Macedonian"),
                            ("ml", "Malayalam"),
                            ("mr", "Marathi"),
                            ("es-mx", "Mexican Spanish"),
                            ("mn", "Mongolian"),
                            ("ne", "Nepali"),
                            ("es-ni", "Nicaraguan Spanish"),
                            ("nb", "Norwegian Bokmål"),
                            ("nn", "Norwegian Nynorsk"),
                            ("os", "Ossetic"),
                            ("fa", "Persian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("pa", "Punjabi"),
                            ("ro", "Romanian"),
                            ("ru", "Russian"),
                            ("gd", "Scottish Gaelic"),
                            ("sr", "Serbian"),
                            ("sr-latn", "Serbian Latin"),
                            ("zh-hans", "Simplified Chinese"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("es", "Spanish"),
                            ("sw", "Swahili"),
                            ("sv", "Swedish"),
                            ("ta", "Tamil"),
                            ("tt", "Tatar"),
                            ("te", "Telugu"),
                            ("th", "Thai"),
                            ("zh-hant", "Traditional Chinese"),
                            ("tr", "Turkish"),
                            ("udm", "Udmurt"),
                            ("uk", "Ukrainian"),
                            ("hsb", "Upper Sorbian"),
                            ("ur", "Urdu"),
                            ("es-ve", "Venezuelan Spanish"),
                            ("vi", "Vietnamese"),
                            ("cy", "Welsh"),
                        ],
                        max_length=7,
                    ),
                ),
            ],
            options={
                "verbose_name": "Common name",
                "verbose_name_plural": "Common names",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Distribution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("protected", models.NullBooleanField(verbose_name="Protected by law")),
                (
                    "red_list_status",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("LEAST_CONCERN", "Least Concern"),
                            ("NEAR_THREATENED", "Near Threatened"),
                            ("VULNERABLE", "Vulnerable"),
                            ("ENDANGERED", "Endangered"),
                            ("CRITICALLY_ENDANGERED", "Critically Endangered"),
                            ("EXTINCT_IN_WILD", "Extinct in the Wild"),
                            ("EXTINCT", "Extinct"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="regions.Region"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator("^[A-Z][a-z]+$")
                        ],
                    ),
                ),
                ("slug", models.SlugField(blank=True)),
            ],
            options={
                "verbose_name": "Family",
                "verbose_name_plural": "Families",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Genus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator("^[A-Z][a-z]+$")
                        ],
                    ),
                ),
                ("slug", models.SlugField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Genera",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InvalidName",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Invalid name",
                "verbose_name_plural": "Invalid names",
            },
        ),
        migrations.CreateModel(
            name="Month",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z][a-z]+ [a-z\\.]+$"
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Species",
                "verbose_name_plural": "Species",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SpeciesDescription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("af", "Afrikaans"),
                            ("sq", "Albanian"),
                            ("ar", "Arabic"),
                            ("es-ar", "Argentinian Spanish"),
                            ("ast", "Asturian"),
                            ("en-au", "Australian English"),
                            ("az", "Azerbaijani"),
                            ("eu", "Basque"),
                            ("be", "Belarusian"),
                            ("bn", "Bengali"),
                            ("bs", "Bosnian"),
                            ("pt-br", "Brazilian Portuguese"),
                            ("br", "Breton"),
                            ("en-gb", "British English"),
                            ("bg", "Bulgarian"),
                            ("my", "Burmese"),
                            ("ca", "Catalan"),
                            ("es-co", "Colombian Spanish"),
                            ("hr", "Croatian"),
                            ("cs", "Czech"),
                            ("da", "Danish"),
                            ("nl", "Dutch"),
                            ("en", "English"),
                            ("eo", "Esperanto"),
                            ("et", "Estonian"),
                            ("fi", "Finnish"),
                            ("fr", "French"),
                            ("fy", "Frisian"),
                            ("gl", "Galician"),
                            ("ka", "Georgian"),
                            ("de", "German"),
                            ("el", "Greek"),
                            ("he", "Hebrew"),
                            ("hi", "Hindi"),
                            ("hu", "Hungarian"),
                            ("is", "Icelandic"),
                            ("io", "Ido"),
                            ("id", "Indonesian"),
                            ("ia", "Interlingua"),
                            ("ga", "Irish"),
                            ("it", "Italian"),
                            ("ja", "Japanese"),
                            ("kab", "Kabyle"),
                            ("kn", "Kannada"),
                            ("kk", "Kazakh"),
                            ("km", "Khmer"),
                            ("ko", "Korean"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("dsb", "Lower Sorbian"),
                            ("lb", "Luxembourgish"),
                            ("mk", "Macedonian"),
                            ("ml", "Malayalam"),
                            ("mr", "Marathi"),
                            ("es-mx", "Mexican Spanish"),
                            ("mn", "Mongolian"),
                            ("ne", "Nepali"),
                            ("es-ni", "Nicaraguan Spanish"),
                            ("nb", "Norwegian Bokmål"),
                            ("nn", "Norwegian Nynorsk"),
                            ("os", "Ossetic"),
                            ("fa", "Persian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("pa", "Punjabi"),
                            ("ro", "Romanian"),
                            ("ru", "Russian"),
                            ("gd", "Scottish Gaelic"),
                            ("sr", "Serbian"),
                            ("sr-latn", "Serbian Latin"),
                            ("zh-hans", "Simplified Chinese"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("es", "Spanish"),
                            ("sw", "Swahili"),
                            ("sv", "Swedish"),
                            ("ta", "Tamil"),
                            ("tt", "Tatar"),
                            ("te", "Telugu"),
                            ("th", "Thai"),
                            ("zh-hant", "Traditional Chinese"),
                            ("tr", "Turkish"),
                            ("udm", "Udmurt"),
                            ("uk", "Ukrainian"),
                            ("hsb", "Upper Sorbian"),
                            ("ur", "Urdu"),
                            ("es-ve", "Venezuelan Spanish"),
                            ("vi", "Vietnamese"),
                            ("cy", "Welsh"),
                        ],
                        max_length=7,
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SubFamily",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator("^[A-Z][a-z]+$")
                        ],
                    ),
                ),
                ("slug", models.SlugField(blank=True)),
                (
                    "family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ants.Family",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub Family",
                "verbose_name_plural": "Sub Families",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AntSpecies",
            fields=[
                (
                    "species_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ants.Species",
                    ),
                ),
                (
                    "colony_structure",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MONO", "Monogynous"),
                            ("OLIGO", "Oligogynous"),
                            ("POLY", "Polygynous"),
                        ],
                        max_length=4,
                        null=True,
                        verbose_name="Colony Structure",
                    ),
                ),
                (
                    "worker_polymorphism",
                    models.NullBooleanField(verbose_name="Worker polymorphism"),
                ),
                (
                    "nutrition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LEAVES", "Leaves, grass and other vegetables"),
                            (
                                "OMNIVOROUS",
                                "Omnivorous (sugar water, honey, insects, meat, seeds,         nuts etc.)",
                            ),
                            (
                                "SEEDS",
                                "Mainly seeds and nuts but dead insects and sugar water,         honey too.",
                            ),
                            ("SUGAR_INSECTS", "Insects, meat, sugar water, honey etc."),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Nutrition",
                    ),
                ),
                (
                    "flight_months",
                    models.ManyToManyField(
                        blank=True,
                        to="ants.Month",
                        verbose_name="Nuptial flight months",
                    ),
                ),
            ],
            options={
                "verbose_name": "Species",
                "verbose_name_plural": "Species",
                "ordering": ["name"],
            },
            bases=("ants.species",),
        ),
        migrations.AddField(
            model_name="speciesdescription",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ants.Species"
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="genus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ants.Genus",
            ),
        ),
        migrations.AddField(
            model_name="invalidname",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ants.Species"
            ),
        ),
        migrations.AddField(
            model_name="genus",
            name="sub_family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ants.SubFamily",
            ),
        ),
        migrations.AddField(
            model_name="distribution",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ants.Species"
            ),
        ),
        migrations.AddField(
            model_name="commonname",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ants.Species"
            ),
        ),
        migrations.AddField(
            model_name="antsize",
            name="ant_species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ants.AntSpecies"
            ),
        ),
    ]
