# Generated by Django 2.0.2 on 2018-03-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['name'], 'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
        migrations.AlterModelOptions(
            name='genus',
            options={'ordering': ['name'], 'verbose_name_plural': 'Genera'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name'], 'verbose_name': 'Species', 'verbose_name_plural': 'Species'},
        ),
        migrations.AlterModelOptions(
            name='subfamily',
            options={'ordering': ['name'], 'verbose_name': 'Sub Family', 'verbose_name_plural': 'Sub Families'},
        ),
        migrations.RemoveField(
            model_name='speciesdescription',
            name='html',
        ),
        migrations.AddField(
            model_name='speciesdescription',
            name='description',
            field=models.TextField(default='NONE'),
            preserve_default=False,
        ),
    ]
