# Generated by Django 2.0.3 on 2018-03-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ants', '0002_auto_20180315_0651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonname',
            options={'ordering': ['name'], 'verbose_name': 'Common name', 'verbose_name_plural': 'Common names'},
        ),
    ]
