# Generated by Django 2.0.4 on 2018-04-03 23:42

import ants.models
from decimal import Decimal
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ants', '0002_distribution_native'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antsize',
            name='maximum',
            field=ants.models.SizeField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='antsize',
            name='minimum',
            field=ants.models.SizeField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
