# Generated by Django 2.0.3 on 2018-03-24 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0006_auto_20180324_2310'),
        ('ants', '0003_auto_20180324_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntRegion',
            fields=[
                ('region_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='regions.Region')),
                ('ant_list_complete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('regions.region',),
        ),
        migrations.RemoveField(
            model_name='species',
            name='countries',
        ),
        migrations.AlterField(
            model_name='species',
            name='regions',
            field=models.ManyToManyField(blank=True, to='ants.AntRegion', verbose_name='Regions'),
        ),
    ]
