# Generated by Django 2.0.3 on 2018-03-24 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ants', '0004_auto_20180324_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antregion',
            options={},
        ),
    ]
