# Generated by Django 2.0.4 on 2018-04-30 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ants', '0004_auto_20180404_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z][a-z]+ [a-z\\.]+$', 'Enter a valid species name.')]),
        ),
    ]
