# Generated by Django 2.0.3 on 2018-03-24 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ants', '0005_auto_20180324_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antspecies',
            options={'ordering': ['name'], 'verbose_name': 'Species', 'verbose_name_plural': 'Species'},
        ),
    ]
