# Generated by Django 2.0.3 on 2018-03-25 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0007_auto_20180324_2348'),
        ('ants', '0006_auto_20180324_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protected', models.BooleanField()),
                ('red_list_status', models.TextField(blank=True, choices=[('LEAST_CONCERN', 'Least Concern'), ('NEAR_THREATENED', 'Near Threatened'), ('VULNERABLE', 'Vulnerable'), ('ENDANGERED', 'Endangered'), ('CRITICALLY_ENDANGERED', 'Critically Endangered'), ('EXTINCT_IN_WILD', 'Extinct in the Wild'), ('EXTINCT', 'Extinct')], max_length=40, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.Region')),
            ],
        ),
        migrations.RemoveField(
            model_name='species',
            name='regions',
        ),
        migrations.AddField(
            model_name='distribution',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ants.Species'),
        ),
    ]
