# Generated by Django 2.0.3 on 2018-03-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ants', '0007_auto_20180325_2226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObsoleteName',
            new_name='InvalidName',
        ),
        migrations.AlterModelOptions(
            name='invalidname',
            options={'verbose_name': 'Invalid name', 'verbose_name_plural': 'Invalid names'},
        ),
        migrations.AlterField(
            model_name='distribution',
            name='protected',
            field=models.BooleanField(verbose_name='Protected by law'),
        ),
    ]
