# Generated by Django 2.2 on 2019-04-28 13:58

from django.db import migrations

import ants.managers


class Migration(migrations.Migration):
    dependencies = [
        ("ants", "0013_auto_20190428_1254"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="antspecies",
            options={
                "ordering": ("genus__name", "ordering", "name"),
                "verbose_name": "Species",
                "verbose_name_plural": "Species",
            },
        ),
        migrations.AlterModelOptions(
            name="species",
            options={
                "ordering": ("genus__name", "ordering", "name"),
                "verbose_name": "Species",
                "verbose_name_plural": "Species",
            },
        ),
        migrations.AlterModelManagers(
            name="antspecies",
            managers=[
                ("objects", ants.managers.AntSpeciesManager()),
            ],
        ),
    ]
