# Generated by Django 2.2.2 on 2019-06-11 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ants', '0016_auto_20190428_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonname',
            options={'ordering': ['language', 'name'], 'verbose_name': 'Common name', 'verbose_name_plural': 'Common names'},
        ),
        migrations.AlterModelOptions(
            name='invalidname',
            options={'ordering': ['name'], 'verbose_name': 'Invalid name', 'verbose_name_plural': 'Invalid names'},
        ),
        migrations.AlterField(
            model_name='distribution',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ants.AntSpecies'),
        ),
    ]
