# Generated by Django 2.2.2 on 2019-06-17 18:11

import ants.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ants', '0021_auto_20190617_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntSpeciesDistribution',
            fields=[
            ],
            options={
                'verbose_name': 'Species distribution',
                'verbose_name_plural': 'Species distributions',
                'ordering': ('genus__name', 'ordering', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ants.antspecies',),
            managers=[
                ('objects', ants.managers.AntSpeciesManager()),
            ],
        ),
    ]
