# Generated by Django 2.2.2 on 2019-06-17 18:11

from django.db import migrations

import ants.managers


class Migration(migrations.Migration):
    dependencies = [
        ("ants", "0021_auto_20190617_1953"),
    ]

    operations = [
        migrations.CreateModel(
            name="AntSpeciesDistribution",
            fields=[],
            options={
                "verbose_name": "Species distribution",
                "verbose_name_plural": "Species distributions",
                "ordering": ("genus__name", "ordering", "name"),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("ants.antspecies",),
            managers=[
                ("objects", ants.managers.AntSpeciesManager()),
            ],
        ),
    ]
