# Generated by Django 2.2.2 on 2019-06-19 20:51

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ants', '0022_antspeciesdistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='antspecies',
            name='flight_climate',
            field=models.CharField(blank=True, choices=[('m', 'Moderate temperature'), ('w', 'Warm temperature'), ('s', 'Sticky weather')], max_length=1, null=True, verbose_name='Flight climate'),
        ),
        migrations.AddField(
            model_name='antspecies',
            name='flight_hour_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, help_text='Note that the upper value is not included so if you want to enter 25 - 28 you have to enter 25 - 29', null=True, validators=[django.contrib.postgres.validators.RangeMinValueValidator(1), django.contrib.postgres.validators.RangeMaxValueValidator(25)], verbose_name='Flight hour range'),
        ),
    ]
