# Generated by Django 2.2.3 on 2019-07-13 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ants", "0023_auto_20190619_2251"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distribution",
                to="regions.Region",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distribution",
                to="ants.AntSpecies",
            ),
        ),
    ]
