# Generated by Django 2.2.3 on 2019-07-13 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ants", "0024_auto_20190713_1322"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antsize",
            name="ant_species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sizes",
                to="ants.AntSpecies",
            ),
        ),
        migrations.AlterField(
            model_name="invalidname",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invalid_names",
                to="ants.Species",
            ),
        ),
    ]
