# Generated by Django 2.2.3 on 2019-07-14 12:14

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ants', '0025_auto_20190713_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonname',
            options={'ordering': ['name'], 'verbose_name': 'Common name', 'verbose_name_plural': 'Common names'},
        ),
        migrations.AddField(
            model_name='antspecies',
            name='main_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images', verbose_name='Main image'),
        ),
    ]
