# Generated by Django 2.2.3 on 2019-07-14 20:35

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ants', '0026_auto_20190714_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntSpeciesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', sorl.thumbnail.fields.ImageField(upload_to='images', verbose_name='Image file')),
                ('caption', models.TextField(blank=True)),
                ('alt', models.TextField(blank=True, verbose_name='Alternative text')),
            ],
            options={
                'verbose_name': 'Ant species image',
                'verbose_name_plural': 'Ant species images',
            },
        ),
        migrations.RemoveField(
            model_name='antspecies',
            name='main_image'
        ),
        migrations.AddField(
            model_name='antspecies',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ants.AntSpeciesImage'),
        ),
        migrations.AddField(
            model_name='antspeciesimage',
            name='ant_species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ants.AntSpecies'),
        ),
    ]
