# Generated by Django 2.2.3 on 2019-07-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ants', '0028_auto_20190715_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='antspeciesimage',
            name='source_caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Source caption'),
        ),
        migrations.AddField(
            model_name='antspeciesimage',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='Image source'),
        ),
    ]
