# Generated by Django 2.2.3 on 2019-07-27 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ants', '0031_antregion_antmaps_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution', to='ants.AntRegion'),
        ),
    ]
