# Generated by Django 2.2.3 on 2019-08-02 05:25

from decimal import Decimal

import django.core.validators
from django.db import migrations

import ants.models


class Migration(migrations.Migration):
    dependencies = [
        ("ants", "0032_auto_20190727_1143"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antsize",
            name="minimum",
            field=ants.models.SizeField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Minimum (mm)",
            ),
        ),
    ]
