# Generated by Django 2.2.4 on 2019-08-26 10:12

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ants", "0033_auto_20190802_0525"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speciesdescription",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
    ]
