# Generated by Django 3.2.2 on 2021-05-10 03:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ants', '0036_auto_20200911_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genus',
            name='sub_family',
        ),
        migrations.AddField(
            model_name='species',
            name='author',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='group',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z][a-z]+$')])),
                ('slug', models.SlugField(editable=False)),
                ('sub_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ants.subfamily')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='genus',
            name='tribe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ants.tribe'),
        ),
    ]
