# Generated by Django 3.2.2 on 2021-05-11 00:14

from django.db import migrations

import ants.managers


class Migration(migrations.Migration):
    dependencies = [
        ("ants", "0037_auto_20210510_0306"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="subfamily",
            managers=[
                ("objects", ants.managers.TaxonomicRankManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="tribe",
            managers=[
                ("objects", ants.managers.TaxonomicRankManager()),
            ],
        ),
    ]
