# Generated by Django 3.2.2 on 2021-05-12 02:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ants", "0039_species_valid"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="distribution",
            unique_together={("species", "region")},
        ),
    ]
