# Generated by Django 5.2.14 on 2026-06-07 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ants', '0050_speciesdifficultyrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('PROTEIN', 'Protein (feeder insects)'), ('SUGAR', 'Sugar (honey, syrups)'), ('SEEDS', 'Seeds'), ('NUTS', 'Nuts'), ('PLANT', 'Leaves'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('ordering', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Food item',
                'verbose_name_plural': 'Food items',
                'ordering': ['category', 'ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpeciesFoodRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance', models.PositiveSmallIntegerField(choices=[(1, 'Really liked'), (2, 'Accepted (not very interested)'), (3, 'Ignored')])),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_ratings', to='ants.fooditem')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_ratings', to='ants.antspecies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Species food rating',
                'verbose_name_plural': 'Species food ratings',
                'unique_together': {('species', 'food_item', 'user')},
            },
        ),
    ]
