# Generated by Django 5.2.15 on 2026-06-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ants', '0055_fooditem_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
