# Generated by Django 5.2.15 on 2026-06-19 19:20

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ants', '0056_fooditem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='food_items', verbose_name='Image file'),
        ),
    ]
