# Generated by Django 5.2.15 on 2026-06-20 19:34

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ants', '0057_fooditem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesfoodrating',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='food_ratings', verbose_name='Image file'),
        ),
    ]
