# Generated by Django 5.2.15 on 2026-06-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ants', '0058_speciesfoodrating_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesfoodrating',
            name='condition',
            field=models.CharField(blank=True, choices=[('ALIVE', 'Alive'), ('FRESHLY_KILLED', 'Freshly killed'), ('FRESH', 'Fresh'), ('SCALDED', 'Scalded'), ('FROZEN', 'Frozen (thawed)'), ('DRIED', 'Dried')], max_length=20, null=True),
        ),
    ]
