# Generated by Django 5.2.15 on 2026-07-14 00:00
#
# Structural migration: introduces FoodRatingSubmission (shared
# acceptance/condition/comment) and RatingPhoto (multiple photos per
# submission), and trims SpeciesFoodRating down to a thin per-species link
# row pointing at a submission.
#
# No production data exists yet for SpeciesFoodRating, so this migration
# does NOT preserve existing rows -- it deletes them first (see the
# RunPython step below) rather than attempting a data-preserving backfill.
# Any local/dev SpeciesFoodRating rows (including their images) will be
# lost when this migration runs.

import django.db.models.deletion
import sorl.thumbnail.fields
from django.conf import settings
from django.db import migrations, models


def delete_existing_species_food_ratings(apps, schema_editor):
    SpeciesFoodRating = apps.get_model("ants", "SpeciesFoodRating")
    SpeciesFoodRating.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ants', '0059_speciesfoodrating_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(delete_existing_species_food_ratings, migrations.RunPython.noop),
        migrations.CreateModel(
            name='FoodRatingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance', models.PositiveSmallIntegerField(choices=[(1, 'Ignored'), (2, 'Hardly interested'), (3, 'Moderately interested'), (4, 'Above average interest'), (5, 'Extremely interested (strong recruitment)')])),
                ('condition', models.CharField(blank=True, choices=[('ALIVE', 'Alive'), ('FRESHLY_KILLED', 'Freshly killed'), ('FRESH', 'Fresh'), ('SCALDED', 'Scalded'), ('FROZEN', 'Frozen (thawed)'), ('DRIED', 'Dried')], max_length=20, null=True)),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_submissions', to='ants.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_rating_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Food rating submission',
                'verbose_name_plural': 'Food rating submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RatingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='food_ratings', verbose_name='Image file')),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ants.foodratingsubmission')),
            ],
            options={
                'verbose_name': 'Rating photo',
                'verbose_name_plural': 'Rating photos',
                'ordering': ['ordering', 'created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='speciesfoodrating',
            name='acceptance',
        ),
        migrations.RemoveField(
            model_name='speciesfoodrating',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='speciesfoodrating',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='speciesfoodrating',
            name='image',
        ),
        migrations.AddField(
            model_name='speciesfoodrating',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_food_ratings', to='ants.foodratingsubmission'),
            preserve_default=False,
        ),
    ]
