# Generated by Django 5.2.15 on 2026-07-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ants', '0060_food_rating_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image_author',
            field=models.CharField(blank=True, help_text='Name of the photographer/creator, for Creative Commons attribution.', max_length=200, verbose_name='Image author'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='image_license',
            field=models.CharField(blank=True, choices=[('CC0-1.0', 'CC0 1.0 (Public Domain)'), ('CC-BY-2.0', 'CC BY 2.0'), ('CC-BY-3.0', 'CC BY 3.0'), ('CC-BY-4.0', 'CC BY 4.0'), ('CC-BY-SA-2.0', 'CC BY-SA 2.0'), ('CC-BY-SA-3.0', 'CC BY-SA 3.0'), ('CC-BY-SA-4.0', 'CC BY-SA 4.0'), ('CC-BY-NC-2.0', 'CC BY-NC 2.0'), ('CC-BY-NC-SA-2.0', 'CC BY-NC-SA 2.0')], help_text='Only needed if the image is Creative Commons licensed rather than your own work.', max_length=20, verbose_name='Image license'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='image_source_url',
            field=models.URLField(blank=True, help_text='Link to the original image or its source page.', verbose_name='Image source URL'),
        ),
    ]
