# Generated by Django 5.2.15 on 2026-07-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ants', '0061_fooditem_image_author_fooditem_image_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image_author',
            field=models.CharField(blank=True, help_text='Name of the photographer/creator, for image attribution.', max_length=200, verbose_name='Image author'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image_license',
            field=models.CharField(blank=True, choices=[('CC0-1.0', 'CC0 1.0 (Public Domain)'), ('CC-BY-2.0', 'CC BY 2.0'), ('CC-BY-3.0', 'CC BY 3.0'), ('CC-BY-4.0', 'CC BY 4.0'), ('CC-BY-SA-2.0', 'CC BY-SA 2.0'), ('CC-BY-SA-3.0', 'CC BY-SA 3.0'), ('CC-BY-SA-4.0', 'CC BY-SA 4.0'), ('CC-BY-NC-2.0', 'CC BY-NC 2.0'), ('CC-BY-NC-SA-2.0', 'CC BY-NC-SA 2.0'), ('GFDL', 'GNU Free Documentation License')], help_text='Only needed if the image is licensed (e.g. Creative Commons, GFDL) rather than your own work.', max_length=20, verbose_name='Image license'),
        ),
    ]
